### ISSUE TITLE
纵向转横向的Tab内容无法自适应缩放

### ISSUE THREAD

**Issue by boshitlove** [xiaosu95/tab-swiper#1]
是这样的，我在调用您的Tab swiper时发现到当我拿手机纵向转成横向观看的时后，tab内容的宽度无法立即自适应缩放，导致在切换Tabs的时后内容会跑版，必须要重新整理后才能正常fit，从横向转成纵向也会有相同的情形，我看了js挡案似乎是因为100vw的关系，这部份是否可以改善呢?谢谢

**Comment by xiaosu95** [comment]
不好意思，最近没时间看。这个bug是没有resize导致的，最新的代码提交了。主要加了
window.addEventListener('resize', function () {
        this.width = this.ele.clientWidth; // 容器宽度
        this.height = this.ele.clientHeight; // 容器高度
        this.totalWidth = this.width * this.containers.length;
        this.changePage(this.nowIndex)
      }.bind(this))

**Comment by boshitlove** [comment]
谢谢您的回覆，我再试试看
